services:
  psql:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - PSQL_VERSION=${PSQL_VERSION}
      tags:
      - ghcr.io/bluestep-systems/psql:latest
      - ghcr.io/bluestep-systems/psql:${PSQL_VERSION}
    image: ghcr.io/bluestep-systems/psql
